apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: "2024-06-02T13:49:49Z"
  generation: 2
  labels:
    app: chat-app
    app.kubernetes.io/component: chat-app
    app.kubernetes.io/instance: chat-app
  name: chat-app
  namespace: dominik-dev
  resourceVersion: "4398659901"
  uid: ca48b871-b87d-4531-a705-957c72b57713
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: chat-app:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      uri: git@github.com:dominiksaul/HEIG-VD-cld-chatapp.git
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: nodejs:18-ubi8
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
  - github:
      secret: 4YtgJXspUKuTL5k1_nPr
    type: GitHub
  - generic:
      secret: j5U6VwXszh5MNQCj9LH7
    type: Generic
  - type: ConfigChange
  - imageChange: {}
    type: ImageChange
status:
  imageChangeTriggers:
  - from:
      name: nodejs:18-ubi8
      namespace: openshift
    lastTriggerTime: "2024-06-02T13:49:49Z"
    lastTriggeredImageID: image-registry.openshift-image-registry.svc:5000/openshift/nodejs@sha256:f1b75cc9dfa248ec850d60fca11b04503de6d767190f6ffa718f7dfb433a0cb8
  lastVersion: 1
